apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-sse-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/telemetria/stream
            pathType: Exact
            backend:
              service:
                name: backend-api-buses
                port:
                  number: 80
